### PR TITLE
Adjustments to make nav-menu agnostic for all themes

### PR DESCRIPTION
**Pull request by dfosco**

### CODE REVIEW

**Comment by dfosco** [comment]
@brenoc @tamorim @gkozlowaski Please review.

**Comment by tamorim** [comment]
@dfosco Please rebase your branch with master, it will remove from your commit the assets files!

**Comment by dfosco** [comment]
@tamorim done! (ノಠ益ಠ)ノ彡┻━┻

**Comment by tamorim** [comment]
@dfosco I merged it without checking properly... The font is too small causing a lot discomfort and why a white background?
I reverted the merge and restored your branch. Unfortunately you'll have to open another PR

**Comment by dfosco** [comment]
The lack of background color was done on Pilates Lovers theme (that has a white background) considering the menu would have a solid color — definitely worse the way it is:

image

I also adjusted font-sizing to have an appropriate sizing, customizing CSS on Pilates Lovers to keep it the way @afonso-praca wanted. 

I'll check how it's looking like and open another PR, but show me a screenshot to make sure we're seeing the same thing — it seemed fine by me.

**Comment by dfosco** [comment]
@tamorim Please see [#3](https://github.com/vtex-apps/nav-menu-desktop/pull/3)

**Pull request merged**
